### ISSUE TITLE
getAttachment not working once crypto is initiated

### ISSUE THREAD

**Issue by victorpease** [calvinmetcalf/crypto-pouch#11]
getAttachment returns missing doc error once the encryption is activated. 
As a workaround, i am using the attachments:true option to get the attachments.

**Comment by calvinmetcalf** [comment]
Yeah it's not supported at the moment

**Comment by victorpease** [comment]
this is my alternative getAttach:

function getAttach(key,index){
		 var dfd = $q.defer();
		 var image;
		 db.get(key,{attachments:true,binary:false})
		  .then(function(result){
			  var name = Object.keys(result._attachments)[index];
			  var attach = result._attachments[name];
			  var url = window.URL || window.webkitURL;
			  image = "data:"+attach.content_type+";base64,"+attach.data;
			  dfd.resolve(image);
		  },function(error){
			  console.log('Error cargando blob:'+error);
		  });
		 return dfd.promise;
	 }
where key is the id of the document and index is the index of the attachment that you want to retrieve. 
Then you can use it like this:

getAttach(id,0).then(function(result){
 image = result;
})

Binary:true doesnt work with crypto activated.
