### ISSUE TITLE
db.crypto is not a function ('undefined')

### ISSUE THREAD

**Issue by paynoattn** [calvinmetcalf/crypto-pouch#15]
Trying to run this in the browser. And I'm at a loss.

`var db = PouchDB('dudes');
db.crypt('password').then(console.log(db))`

returns

`Uncaught TypeError: db.crypt is not a function
    at <anonymous>:2:6
    at Object.InjectedScript._evaluateOn (<anonymous>:875:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:808:34)
    at Object.InjectedScript.evaluate (<anonymous>:664:21)(anonymous function) @ VM33737:2InjectedScript._evaluateOn @ VM33252:875InjectedScript._evaluateAndWrap @ VM33252:808InjectedScript.evaluate @ VM33252:664`

Umm.... File loaded? Yup. 

```
console.log(crypto)
```

```
cryto: {
_subtle: {
  decrypt() {...}
  encrypt() {...}
...
```

Oh cool.

```
function myEncrypt(x) {
  crypto.subtle.encrypt(x)
}
myEncrypt(db);
```

```
Uncaught (in promise) TypeError: Failed to execute 'encrypt' on 'SubtleCrypto': 3 arguments required, but only 1 present.
    at TypeError (native)
    at myEncrypt (<anonymous>:3:17)
    at <anonymous>:2:1
    at Object.InjectedScript._evaluateOn (<anonymous>:875:140)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:808:34)
    at Object.InjectedScript.evaluate (<anonymous>:664:21)
```

Umm, huh?

```
console.log(crypto.self.encrypt);
```

```
encrypt() { [native code] }
```

I'm sooooo lost. I'm guessing native code is crap from V8, since it looks like this is running VM's. Am I right? Honestly, I really need more documentation than add this browserified file like normal.

I tried looking through the source code but then my brain overheated.

Do I need to also download the browseried version of crypto-browserify?

Is it even worth pursuing this? You haven't checked-in for 5 months...

Thanks for your hard work.

**Comment by calvinmetcalf** [comment]
it is `db.crypto` not `db.crypt` that is your first problem, the fact that `crypto` is available is a red herring that doesn't mean what your assuming it does.

If you are not using browserify then don't worry about browserify you just need to load the scrypt at http://wzrd.in/bundle/crypto-pouch after you load pouchdb.

**Comment by paynoattn** [comment]
Sorry, that was a typo in my issue, not my original code. 

![screen shot 2016-01-14 at 8 29 17 am](https://cloud.githubusercontent.com/assets/7308577/12328543/05d868f6-ba99-11e5-93b8-a76400ab40ed.png)

As you can see, everything is loading fine, using PouchDB 5.1.0

![screen shot 2016-01-14 at 8 31 02 am](https://cloud.githubusercontent.com/assets/7308577/12328594/4a7eca22-ba99-11e5-98ff-c2a23378ce5d.png)

Looking back, my original pull request was a bit ... confrontational, maybe thats what happens when posting issues @ 2am. Thanks for your help and all your hard work on this project.

Normally I'd be fine using this in node, but for this specific project (cordova app) I must go nodeless.

**Comment by calvinmetcalf** [comment]
if you are using browserify or some other bundler you should need to add:

```js
var PouchDB = require('pouchdb');
PouchDB.plugin(require('crypto-pouch'));
```

**Comment by paynoattn** [comment]
I'm not at the moment, though I've been thinking about integrating webpack. Is it a requirement?

**Comment by calvinmetcalf** [comment]
no it should, basically the code is looking for PouchDB on window

```js
if (typeof window !== 'undefined' && window.PouchDB) {
  window.PouchDB.plugin(module.exports);
}
```
and that's where it is supposed to be registering itself, I don't think there have been any changes to PouchDB that should prevent that from working but pinging @nolanlawson just to double check

**Comment by nolanlawson** [comment]
One thing you need to be sure to do is include the `pouchdb.crypto.js` script *after* the `pouchdb.js` script. Other than that, not sure what's going on here.

**Comment by paynoattn** [comment]
I have quadruple checked. Crypto-pouch is being loaded after pouchDB. Proof:

![screen shot 2016-01-14 at 11 14 49 pm](https://cloud.githubusercontent.com/assets/7308577/12346763/b2efd030-bb14-11e5-8fc6-1753338a46a3.png)

I also tried removing all other calls to CSS and Javascript aside from the two, and a simple scriptfile running part of the test from your test.js. Tried the unminified version of pouchdb.

Running Chrome 47.0.2526.106 (64-bit) on OSX El Capitan.

Maybe I can try an earlier version of PouchDB. I'll also look into browserfiy/webpack and see if that makes it work, but at that webpoint I may as well just run it an node and include it in my bundle.

Honestly though, I think I'm going to switch to device SQLite/Ciper for this project since it looks like based on the comments in the crypto-pouch browser file it won't run outside Chrome V8 and therefore won't work on iOS Safari.

If you need me to do anything to help debug this let me know.

Thanks again.

**Comment by calvinmetcalf** [comment]
It should work just fine in safari don't know what makes you think it
won't...

**Comment by nolanlawson** [comment]
@paynoattn Are you loading `bundle.js` or `index.js`? You're supposed to load the bundle if you're using `<script>` tags.

**Comment by nolanlawson** [comment]
I've thrown together a little HTML file to demonstrate. I've confirmed that it works in both Firefox and Safari: http://bl.ocks.org/nolanlawson/6e54fcb0ced2011c804c

```html
<html>
<body>
<h1>demo of crypto-pouch</h1>
<pre id="output"></pre>
<script src="//cdn.jsdelivr.net/pouchdb/latest/pouchdb.js"></script>
<script src="http://wzrd.in/standalone/crypto-pouch"></script>
<script>
document.getElementById('output').innerHTML = 'Yo, does db.crypto exist?: ' + new PouchDB('foobar').crypto;
</script>
</body>
</html>

```

Closing this issue unless you still think there's a bug! :) Thanks

**Comment by erik127** [comment]
@paynoattn
I had a similar issue. I just noticed that Nolan uses another script in his example than the one mentioned in readme.md.. 
So instead of using the one linked from the readme page:
http://wzrd.in/bundle/crypto-pouch
I tried this one:
http://wzrd.in/standalone/crypto-pouch

That solved my issue.

**Comment by baotoan1905** [comment]
Hello guys, 
I'm using Require JS to load javascripts files. Any idea how to combine them? I'm getting error when load crypto plugin by using require js.

**Comment by garbados** [comment]
It seems like there's a solution to this issue in the thread, so I'm closing it for now. Everyone, please let me know if you still need help!
