### ISSUE TITLE
RangeError: Trying to access beyond buffer length(…)

### ISSUE THREAD

**Issue by senthil7273** [calvinmetcalf/crypto-pouch#20]
here is code used to enable crypto in pouchDB. I am using cordova+angularjs+pouchdb. i tried the same on chrome too.

```
var password = "xxx";
  thisObj._db = new PouchDB('myDatabase', {adapter: 'websql'});
   thisObj._db.crypto(password)
  .then(function(){
  });
```

when i tried to put a record as mentioned below

```
thisObj._db.put({_id:'s1', name:'senthil', offline:'yes'}).then(function(response){
    console.log(response);
  }).catch(function(error){
    console.log(error);
  });
```

i am getting the follwing error.
`RangeError: Trying to access beyond buffer length(…)`

Am i missing anything  ? or doing in wrong way ?

**Comment by garbados** [comment]
Hi @senthil7273 ! Do you still need help with this? We just published version 4.0 and I invite you to try again with it. I'm closing this issue for now since it's been a while, but I can re-open if you'd like :)
