### ISSUE TITLE
What happens if the user forgets there password?

### ISSUE THREAD

**Issue by markbarton** [calvinmetcalf/crypto-pouch#27]
Trying to think of a worse case scenario - if the local data is encrypted using a user generated password and then they forget it.

Is the local data unrecoverable?  The constraint we have is its a local Javascript application so can be decompiled if the laptop was stolen and the other Windows security measures fail (Secure Login / Bitlocker).

I guess we could store the users password on the server so it could be recovered but of course this is bad practice.  

Any suggestions?

**Comment by calvinmetcalf** [comment]
yes the data would be unrecoverable without knowing the password

**Comment by garbados** [comment]
Closing this issue for now, since it's been a few years :)
