### ISSUE TITLE
TypeError: crypto.pbkdf2 is not a function

### ISSUE THREAD

**Issue by JoellyR** [calvinmetcalf/crypto-pouch#30]
I was just wondering why i keep getting the error 

`TypeError: crypto.pbkdf2 is not a function`

whenever trying use the manual decrypt functions. My app is an ionic app and i am using the browserified version of crypto-pouch. Sorry if you need more just let me know (it's my first time actually posting an issue on GitHub or any forum xD )

**Comment by garbados** [comment]
Hi @JoellyR ! Do you still need help? We've just published version 4.0 and I invite you to try again and let me know how it goes. I'm closing this issue for now since it's been a long time, but I can re-open it if you'd like :)
