### ISSUE TITLE
Could you pls provide license information on crypto-pouch lib for me?

### ISSUE THREAD

**Issue by zhangsword** [calvinmetcalf/crypto-pouch#31]
Hi Dear

I am thinking if apply crypto-pouch lib on my project.
Could you pls provide license information for me?
Thanks on advance!

**Comment by calvinmetcalf** [comment]
MIT license https://github.com/calvinmetcalf/crypto-pouch/blob/1aa2a1fb7a8c5f5723985d2e7a71ced49b117ffc/package.json#L21

**Comment by sophokles73** [comment]
Maybe you can include a LICENSE.txt file to the root folder of the project so that
* GitHub can pick it up and include the license in the project metadata and
* visitors of the project can immediately see which license you are using

**Comment by calvinmetcalf** [comment]
done
