### ISSUE TITLE
Crypto-Pouch and typescript

### ISSUE THREAD

**Issue by tubauwe** [calvinmetcalf/crypto-pouch#40]
I'm trying to use Crypto-Pouch in an Ionic 2 application. After switching to Ionic 2 RC0 I managed after a couple of days to use PouchDB again. But I'm not able to use Crypto-Pouch.

Because Ionic 2 suggest to use typescript and not javascript, I need a type definition for Crypto-Pouch. Do you know, how to do this? Thanks in advance.

In the Ionic forum I described in [this topic](https://forum.ionicframework.com/t/using-plugin-crypto-pouch-with-pouchdb-in-rc0-uncaught-typeerror/66299) my Problem.

**Comment by calvinmetcalf** [comment]
I don't use typescript so I'm not really sure how I can help you.  I don't think you HAVE to use typescript so if you don't really know how to use it either, then maybe don't.

**Comment by tubauwe** [comment]
The error message is:

`Uncaught TypeError: Cannot read property 'listenerCount' of undefined      _stream_readable.js:38`

Do you have an idea to solve?

**Comment by hadrien-toma** [comment]
Same error for me as described [here](https://forum.ionicframework.com/t/using-plugin-crypto-pouch-with-pouchdb-in-rc0-uncaught-typeerror/66299) too.

**Comment by tubauwe** [comment]
After the latest updates in build process of ionic, I tried using crypto-pouch again. By using the following lines in my data provider, I get no error messages first (not trying to encrypt the database):

    import PouchDB from 'pouchdb';
    import CryptoPouch from 'crypto-pouch';
    PouchDB.plugin(CryptoPouch);

But if I insert the _crypto_ command in the code, I get one of the following errors:

1. Trying only _myDB.crypto('password');_ I get this error message:

    _TypeError: Failed to execute 'importKey' on 'SubtleCrypto': The provided value is not of type '(ArrayBufferView or ArrayBufferView or Dictionary)'_

2. Trying this

    _myDB.crypto('password').then((st) => {
        console.log(st);
     }_

     I get this error message:

     _TypeError: Cannot read property 'then' of undefined_

I think I'm a step ahead now, but I don't know to solve it completely. Can you help me? Thanks in advance.

**Comment by calvinmetcalf** [comment]
2 shouldn't work any more as of version 2, 

1 is a bug that I will fix either latter today or tommorow, for now just run 

`myDB.crypto(Buffer.from('password', 'utf8'))`

**Comment by calvinmetcalf** [comment]
ok new version of native-crypto published, reinstall your deps and try again
