### ISSUE TITLE
uglifyjs failed: SyntaxError: Unexpected token: name (check)

### ISSUE THREAD

**Issue by timofeysie** [calvinmetcalf/crypto-pouch#45]
Hi, I am using crypto-pouch in an Ionic 2 app.  Everything works as expected during testing in the browser, but when I try to build the project (ionic build ios), I get the following error:
```
[08:27:12] uglifyjs failed: SyntaxError: Unexpected token: name (check)
[08:27:12] ionic-app-script task: "build"
[08:27:12] Error: SyntaxError: Unexpected token: name (check)
```
I tried changing the "uglify-js" to "git+https://github.com/mishoo/UglifyJS2.git#harmony" in the node_modules/@ionic/app-scripts/package.json as recommended [here](https://github.com/driftyco/ionic-app-scripts/issues/239), but it does not solve the error.

Since there is no 'check' in my code, I looked at the most recently installed lib, "crypto-pouch": "^3.1.0".

Removing the lib allows the build to complete.

On the Ionic issue above, after I posted about this problem, they said this might be "trying to minify that library on it's own independent from app-scripts or ionic." 

I'm trying out transform-pouch with crypto-js now, but I would prefer to use crypto-pouch.

Any ideas regarding this issue?

**Comment by calvinmetcalf** [comment]
it looks like the issue is with whatever is bundling the app is not running the babelify transfrom, I believe ionic uses rollup, so you'd want to make sure to use the [auto transform plugin](https://github.com/calvinmetcalf/rollup-plugin-auto-transform)

**Comment by timofeysie** [comment]
Thanks for the response on that.  How do you use that plugin?  The readme says it uses a key in the package.json, but there is no documentation other than that.

**Comment by calvinmetcalf** [comment]
You use it with your rollup config where ever that is

**Comment by calvinmetcalf** [comment]
ionic uses [rollup](http://rollupjs.org/guide/) to build things, somewhere in ionic there is a way to specify the rollup plugins you want, that would be where you say that you want to use the auto-transform-plugin

**Comment by timofeysie** [comment]
I know when I started this project, it was using Rollup.  I wasn't sure when they changed to Webpack (RC 2?), or tow what extent.  [This pull request](https://github.com/driftyco/ionic-app-scripts/pull/158) was merged in Octover, and Webpack is definitely building the project during ```$ ionic serve```.  

However, rollup@0.36.3 is in the package.json, along with webpack@2.1.0-beta.28, but the ```$ ionic build ios``` command doesn't show output from either of these.  I'm on a different branch of the project now so will get back to this and try to add the auto transform plugin again then.

**Comment by calvinmetcalf** [comment]
ok then if it's webpack it should handle the that then, I'm generally not super familiar with ionic so you may have to get help there about how to configure it

**Comment by mvkirk** [comment]
Hi everyone.

@calvinmetcalf, I have the same problem using crypto-pouch with ionic2. Is the auto transform plugin the correct solution ? Does it works for you ?

**Comment by timofeysie** [comment]
Hi @mvkirk, 
With the [transform-pouch](https://github.com/nolanlawson/transform-pouch) plugin, you have to create your own encryptions when you store things in the db.  I used [crypto-js](https://code.google.com/archive/p/crypto-js/) which does not work for an entire array of objects.  You have to loop thru each object and encrypt/decrypt those each.
So that makes the whole process a lot more hands on.  I would prefer to use this repo.

But this issue is about a failing ionic build ios command.  Starting over again with crypto-pouch today, when installing it via npm, there is the following output:
```
$ npm install crypto-pouch --save
ehs-hybrid-prototype-2@ /Users/timcurchod/repos/ehs-prototype-2
├── UNMET PEER DEPENDENCY @angular/compiler@2.0.0
├── UNMET PEER DEPENDENCY @angular/core@2.0.0
├─┬ crypto-pouch@3.1.1 
│ ├─┬ pouchdb-promise@6.1.0 
│ │ └── lie@3.1.0 
│ └─┬ transform-pouch@1.1.3 
│   ├─┬ es3ify@0.2.2 
│   │ ├── esprima@2.7.3 
│   │ └─┬ jstransform@11.0.3 
│   │   ├── base62@1.1.2 
│   │   ├── esprima-fb@15001.1.0-dev-harmony-fb 
│   │   └── object-assign@2.1.1 
│   ├── inherits@2.0.1 
│   ├── lie@3.0.4 
│   ├── pouchdb-extend@0.1.2 
│   ├── pouchdb-promise@5.4.3 
│   └─┬ pouchdb-wrappers@1.3.6 
│     └── promise-nodify@1.0.2 
└── UNMET PEER DEPENDENCY tslint@~4.0.0

npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/compiler-cli@2.2.3 but none was installed.
npm WARN @ngtools/webpack@1.1.9 requires a peer of @angular/core@2.2.3 but none was installed.
npm WARN codelyzer@2.0.0-beta.3 requires a peer of tslint@~4.0.0 but none was installed.
npm WARN codelyzer@2.0.0-beta.3 requires a peer of @angular/compiler@<=2.3 >=2.2.0 but none was installed.
npm WARN codelyzer@2.0.0-beta.3 requires a peer of @angular/core@<=2.3 >=2.2.0 but none was installed.
```

@calvinmetcalf, I'm guessing that the un-met peer dependency message with tslint could be causing the problem with uglify?

**Comment by calvinmetcalf** [comment]
all of those warnings are related to ionic and angular not with crypto-pouch
