### ISSUE TITLE
crypto-pouch 3.0.0 with pouchdb 6.1.0 fails

### ISSUE THREAD

**Issue by amruthgs** [calvinmetcalf/crypto-pouch#46]
Latest crypto-pouch (3.0.0) does not work with pouchdb 6.1.0.

**Comment by calvinmetcalf** [comment]
What sort of error do you get?

**Comment by amruthgs** [comment]
Basically the PouchDb object is not created since crypto-pouch still uses some of the deprecated api's from pouchdb .

**Comment by calvinmetcalf** [comment]
behind the scenes we use transform pouch, so you may want to open an issue there, that being said tests pass against 6.1.0 so it's obviously not the whole thing that's broken, just some part we don't adequately test for, so could you tell me what exactly you were doing, what you expected to happen and what actually happened ?

**Comment by amruthgs** [comment]
we are trying to upgrade the pouchdb and crypto-pouch to their latest versions from 5.3.2 and 2.0.0 respectively .
We have used angular-pouchdb : 4.1.0  as well. This module is failing since the it does not get the pouchdb object.
We found that crypto-pouch still has references to   window.PouchDB.utils.Promise .utils being deprecated in versions >=5.4.0. of pouchdb .

**Comment by calvinmetcalf** [comment]
the bundle is probably out of date, let me rebuild it

**Comment by calvinmetcalf** [comment]
ok try 3.1.1
