### ISSUE TITLE
Pouchdb6.1.0 with crypto-pouch3.1.1 fails on IE 10,Firefox and safari 5.1.7

### ISSUE THREAD

**Issue by amruthgs** [calvinmetcalf/crypto-pouch#49]
The upgrade works fine on chrome once the existing indexeddb are cleared.
But on the IE, Firefox and safari native-crypto throws an unknown character error and injecting pouchdb in angular fails. 

  Error(`unknown name: ${ name }`);
  Error: Invalid character: '`'

**Comment by calvinmetcalf** [comment]
how are you building it, web pack, browserify, rollup?

**Comment by amruthgs** [comment]
via jspm as bundlesfx

**Comment by garbados** [comment]
Hi @amruthgs ! We just published version 4.0 which doesn't bundle native-crypto anymore. I invite you to try again and let me know how it goes. I'm going to close this issue since it's been a long time, but I can re-open it at your request :)
