### ISSUE TITLE
Uncaught (in promise) error when replicated encrypted database

### ISSUE THREAD

**Issue by petewall** [calvinmetcalf/crypto-pouch#65]
I'm working on an ionic/angular/cordova app that uses PouchDB to store data locally then replicate it to a remote CouchDB database.  I'm only replicating one way.  For now, I'm not concerned with encryption on the remote host.  When I added the `crypto` function, I'm getting this error after initiating replication:

    Runtime Error
    Uncaught (in promise): TypeError: utils.Promise.all is not a function
    TypeError: utils.Promise.all is not a function
        at modifyChanges (http://localhost:8100/build/vendor.js:158813:30)
        at http://localhost:8100/build/vendor.js:158848:16
        at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
        at Object.onInvoke (http://localhost:8100/build/vendor.js:5123:33)
        at t.invoke (http://localhost:8100/build/polyfills.js:3:14916)
        at r.run (http://localhost:8100/build/polyfills.js:3:10143)
        at http://localhost:8100/build/polyfills.js:3:20242
        at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15660)
        at Object.onInvokeTask (http://localhost:8100/build/vendor.js:5114:33)
        at t.invokeTask (http://localhost:8100/build/polyfills.js:3:15581)

I'm using PouchDB 6.4.3 and crypto-pouch 3.1.3.

Here's the code that I'm using to setup the databases:

    private initializeUserDatabase() {
        this.userDB = new PouchDB('myDatabase', { auto_compaction: true });
        this.userDB.crypto('myPassword');

        const remoteUserDB = new PouchDB(`${remoteDatabaseURL}/myDatabase`, {
            auth: { username: ..., password: ... }
        });

        this.userDB.replicate.to(remoteUserDB, {
            live: true,
            retry: true
        }).on('change', function (info) {
            console.log('Replication change: ', info);
        }).on('paused', function () {
            console.log('Replication paused');
        }).on('active', function () {
            console.log('Replication active');
        }).on('denied', function (err) {
            console.log('Replication denied: ', err);
        }).on('complete', function (info) {
            console.log('Replication complete: ', info);
        }).on('error', function (err) {
            console.log('Replication error: ', err);  // <-- Not caught here
        });
    }

The error occurs only after `userDB.replicate` has been called, but it's interesting that it's not caught by the error handler.  If I comment out the call to `userDB.crypto` or the call to `userDB.replicate`, no error will be thrown.

I've tried removing the `auto_compaction` option to the local database, but that didn't change things.  I've tried removing the `live` and `retry` options to the remote database, but that didn't change things.  Also worth noting that I've removed all data from the local database before running, so there should be no local data that needs replicating.

Any ideas on how I can trace this error down?

**Comment by lunedam-git** [comment]
I also am experiencing this problem. Wondering if you got anywhere with your efforts?

**Comment by vickydadhich** [comment]
Experiencing the same problem. Is there any workaround need to make this error free

**Comment by garbados** [comment]
Howdy everyone! We've just released 4.0, which included a lot of dependency changes. I invite you to try again with this new version. Let us know how it goes! If you experience any issues, I can help you debug from there.

**Comment by garbados** [comment]
I'm going to close this issue for now since it's been three years, but I can re-open the issue at your request.
