### ISSUE TITLE
db.crypto - method not available

### ISSUE THREAD

**Issue by front-a-little** [calvinmetcalf/crypto-pouch#7]
I'm using PouchDB 3.4.0 with the browserified version of Crypto-Pouch from the Readme section.
At runtime, the PouchDB instances I create via ````new PouchDB('dbname')```` don't have the "crypto" method.

I include both JS files to my page as described in the Readme section and even rolled back my PouchDB version to 3.1.0.

**Comment by calvinmetcalf** [comment]
just updated the bundle, should work if you try again

**Comment by front-a-little** [comment]
Works now, thanks for the quick fix
