### ISSUE TITLE
Will crypto-pouch be updated?

### ISSUE THREAD

**Issue by thebitguru** [calvinmetcalf/crypto-pouch#72]
Hi, @calvinmetcalf,

First of all, thank you for putting in the initial work and releasing this project.  I noticed that it no longer compiles with Node 13.  Are you still looking at maintaining this project or are you pretty much done at this point?

Thanks!

**Comment by travisbowen** [comment]
I wanted to add another comment as well on this topic to see if he plans on maintaining it anymore.
Thanks!

**Comment by jonathanmcchesney** [comment]
Would be good to get some confirmation for our team to.

**Comment by garbados** [comment]
Yes! It has just been updated to 4.0.0! This is a BREAKING CHANGE but we now use much stronger crypto standards.

**Comment by garbados** [comment]
I'm closing this issue for now, but please let me know if you have any questions or concerns :)
