### ISSUE TITLE
@types/crypto-pouch

### ISSUE THREAD

**Issue by FranklinSimmons** [calvinmetcalf/crypto-pouch#81]
Greetings,

I've written a type definition for crypto-pouch for DefinitelyTyped.  [Here's the fork+push for @types/crypto-pouch](https://github.com/FranklinSimmons/DefinitelyTyped/blob/crypto-pouch/types/crypto-pouch).

I was motivated by [StackOverflow #69264357](https://stackoverflow.com/questions/69264357/crypto-pouch-showing-import-error-in-angular/69270731#69270731) and  [#73](https://github.com/calvinmetcalf/crypto-pouch/issues/73). In both cases the issues are related to missing type definitions which will throw novices off track.

Before issuing a PR on DefinitelyTyped I wanted to drop a few lines here and ask if this is OK with the crypto-pouch maintainers,  or is it otherwise preferable to include a type definition file in this repo, or do you just hate the entire idea?

Thanks!

**Comment by FranklinSimmons** [comment]
@garbados I just noticed your efforts regarding this repo at [#78](https://github.com/calvinmetcalf/crypto-pouch/issues/78). Given the churn involved with your efforts, pushing the TypeScript definitions over to DefinitelyTyped seems a good course.

**Comment by garbados** [comment]
Hey! Thanks for writing up that PR. I'm not opposed to maintaining type definitions in this repo, but I am woefully unfamiliar with writing them effectively. That being the case, I'm content to leave the matter to the community (e.g. you). If you wanted to make a PR against this repo that added typedefs and a way of validating them during testing, I'd be happy to help get it merged!

**Comment by FranklinSimmons** [comment]
Great, I think it's correct to decouple from the repo since TypeScript is really just sugar. I'll push to DefinitelyTyped and submit a PR on the readme.md regarding the type definition for those who care.

**Comment by FranklinSimmons** [comment]
Closing this issue out as the type definitions for crypto-pouch were merged
