### ISSUE TITLE
The authenticity of host 'github.com (140.82.113.3)' can't be established

### ISSUE THREAD

**Issue by FranklinSimmons** [calvinmetcalf/crypto-pouch#82]
I went to clone this repo and was welcomed with this

> $ git clone git@github.com:calvinmetcalf/crypto-pouch.git
> Cloning into 'crypto-pouch'...
> The authenticity of host 'github.com (140.82.113.3)' can't be established.
> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
> Are you sure you want to continue connecting (yes/no)?

What's the deal? I've never encountered this sort of reaction.  Hard to determine if this repo is trusty.

**Comment by FranklinSimmons** [comment]
Well duh.

git clone https://github.com/calvinmetcalf/crypto-pouch

**Comment by garbados** [comment]
No problem, bud! This is my favorite type of bug to get.

FWIW the first time you connect by SSH to a host like github.com, your SSH agent will prompt you to verify that everything looks OK. So, the warning you got isn't unusual; it's just what happens the first time you connect. Using HTTP instead, like you do in your second comment, avoids this issue altogether.
